### ISSUE TITLE
Missing od_files 

### ISSUE THREAD

**Issue by fzoric8** [CANopenNode/CANopenSocket#15]
I've been trying to run tutorial for canopend and concretely I'm stuck on following command: 
`$ app/canopend vcan0 -i 4 -s od4_storage -a od4_storage_auto`. 

Even when I create od4_storage and od4_storage_auto files in app directory as described, I'm still getting same error as before. I'm not able to get vcan0 into operational state. Help would be highly appreciated. Thank you very much.

**Comment by geoffrey-vl** [comment]
I've had some problems with it when some of the files got corrupted. If that's the case be sure to remove these corrupted files and start over from scratch.
If not, posting some terminal output here could help spotting the problem.

**Comment by fzoric8** [comment]
Thank you for fast reply. 
I've tried to delete whole repository and clone it again and rebuild. 

The thing is, I'm getting same output with `candump vcan0` command even after adding `od4_storage` file and `od4_storage_auto` file. 

I've tried to add those files into app folder, but also to canopend folder. It's not really clear from tutorial where exactly those object dictionaries should be added. Dummy `od_storage` and `od_storage_auto` files are located in app directory, whilst there's no directory path included into instructed command for creating `od_storage` files - so it's not exactly straightforward. Could you please explicitly tell me where I have to add those files. Thank you. Terminal output is as follows in both tried cases: 

Terminal output before creating od4_storage and od4_storage auto is as follows: 

`$ app/canopend vcan0 -i 4 -s od4_storage -a od4_storage_auto` 
results with: 
```
app/canopend - starting CANopen device with Node ID 4(0x04), count=1 ...   
app/canopend - communication reset ...    
app/canopend - running ...
```  

`$ candump vcan0` 
results with: 
```
  vcan0  704   [1]  00   
  vcan0  084   [8]  00 50 01 2F F3 FF FF FF   
  vcan0  704   [1]  7F   
  vcan0  704   [1]  7F   
  vcan0  704   [1]  7F   
  vcan0  704   [1]  7F   
  vcan0  704   [1]  7F  
  vcan0  704   [1]  7F...
```

Cases are: 
1. `od4_storage and od4_storage_auto in app folder`
2. `od4_storage and od4_storage_auto in canopend folder`

**Comment by fzoric8** [comment]
I've removed and cloned and remaked everything again. I've also created new `od4_storage` and `od4_storage_auto` in `canopend` directory. 
Make sure that those files are not empty. On Linux Ubuntu 16.04 LTS command `echo - > od4_storage` resulted with empty file. **That may caused problem, I'm not 100% sure**. 

You can also put those files into `app` folder but make sure you provide following path as follows 
```
app/canopend vcan0 -i 4 -s app/od4_storage -a app/od4_storage_auto
```
If problem persists, try to use `sudo make` instead of `make` when making canopend. 
Cheers.

**Comment by CANopenNode** [comment]
> On Linux Ubuntu 16.04 LTS command `echo - > od4_storage` resulted with empty file.

This is strange, it is not the case in my Ubuntu16.04. File must not be empty.

Probably the problem is in `-`. I will change that to something else.

Thank you.
