### ISSUE TITLE
docker gateway

### ISSUE THREAD

**Issue by geoffrey-vl** [CANopenNode/CANopenSocket#18]
Hi,

It's not much of a thing, but I did some tests with running canopen gateway inside a docker container.
It should allow application developers to ease their process.
Its building the canopend daemon from canopensocket repo from source.

Here is the dockerfile: https://github.com/Alphatronics/docker-canopensocket/blob/master/Dockerfile
You can find instructions and pull the image from docker hub: https://hub.docker.com/repository/docker/geoffreyvl/canopensocket
ARMv7 and AMD64 archs are supported.

Let me know if you're interested in having the code shared under the CANopenNode umbrella. Warning: I'm not maintaining this!

**Comment by CANopenNode** [comment]
Hi,

I didn't use Docker before, but I tested your example. Docker seems very interesting.

Would it be enough, if Dockerfile is added to the CANopenSocket project? Plus some instructions in README?

**Comment by geoffrey-vl** [comment]
Well, yes I'd be fine with that. For some embedded developers Docker is not something they touch very often. It depends on the device, off course. On embedded linux there is definitely a growing interest in containerization. Think for example BalenoOS, Mender and Azure IoT Edge.
I'll prepare a PR anytime soon, including README.
