### ISSUE TITLE
Outdated tutorial?

### ISSUE THREAD

**Issue by neomonkey** [CANopenNode/CANopenSocket#2]
SDO transfer works with pican2 and can0 quite nice by the information I got from the tutorial. I was wondering if there is a way to add a part which would explain how the CANopenSocket is handling SDO messages longer than 64 bits. I couldn't figure that out at all (or it is because the same problems as now).

**Comment by CANopenNode** [comment]
SDO communication is described in standard CiA301. Variables <=32 bits are transferred in one request-response. This is so-called expedited transfer. 32 bits is used for SDO protocol. Longer variables are transfered with segmented transfer with multiple request-response pairs. They may optionally be transfered with block transfer.
