### ISSUE TITLE
make failed

### ISSUE THREAD

**Issue by reyanvaldes** [CANopenNode/CANopenSocket#20]
I just follow the steps for making the library but it fails,  maybe I am missing something. I am using Debian Jessie (8), and already installed can-utils.
Please see the attached file. It seems the error is related with  CAN_ERR_CTRL_ACTIVE identifier. Do I need to install other libraries or dependencies?
Thanks for any clue
Reyan
![Make_CANOpenNode](https://user-images.githubusercontent.com/11097772/89132422-fc122880-d4e1-11ea-97ea-4f86af1853c9.PNG)

**Comment by CANopenNode** [comment]
This error showed also here: https://github.com/CANopenNode/CANopenNode/issues/211
It shows with older Linux kernels (definition for CAN_ERR_CRTL_ACTIVE was added to Linux header file in 2014).

I fixed that (made it optional). Please pull latest CANopenNode.

**Comment by reyanvaldes** [comment]
Thank you so much for quick support, yes, it worked, it went thru. I am trying to use as listening only mode to catch the CANOpen frames, and processing. I am not familiar at all with CANOpen, study now little bit. I wondering if you could share what are main functions to call for just lisetning, and how to get the CANOpen frames. Thanks

**Comment by reyanvaldes** [comment]
The make worked it now.

**Comment by CANopenNode** [comment]
You must know the difference between CAN and CANopen.

CAN itself is very interesting and reliable protocol for exchanging messages. It is implemented in Linux kernel. You can interact with it with tools from "can-utils" package, for example "candump" for listening.

CANopen is based on CAN but it is much more. It specifies very useful rules for network control (NMT, heartbeat), access to many different variables in device (SDO), fast and configurable process data (PDO), etc. You have to learn that. It does not make many sense to listen only. For that you can use "candump" or maybe "wireshark" with CANopen addon (https://wiki.wireshark.org/CANopen).
