### ISSUE TITLE
Master always stay preoperational

### ISSUE THREAD

**Issue by ceccocats** [CANopenNode/CANopenSocket#24]
Hi,
Im trying to use canopend as a master like this:
```
canopend can0 -i 1 -c ""
```
I tried to change the state with 
```
canopencomm 1 cmd
```
It accept all the commands changing the states but it never goes operational 
both `canopencomm 1 preop` and `canopencomm 1 start` results in a 7F state and never 05

The slaves instead are working fine.
What Im doing wrong?

thanks,
Francesco

**Comment by CANopenNode** [comment]
Please watch the CAN communication in another terminal window:

    candump can0

You should see the commands from canopencomm

**Comment by CANopenNode** [comment]
See latest release.
