### ISSUE TITLE
canopencomm negative value

### ISSUE THREAD

**Issue by ZygaOGC** [CANopenNode/CANopenSocket#25]
Can not pass negative parameter value while writing SDO. 
If specified as a decimal e.g. "16 write 0x3300 0 i32 -100" help of the command usage is returned. 
If specified as a hex: "16 write 0x3300 0 i32 0xFFFFFFC8" it returns:  [1] ERROR: 101 - Syntax error.

**Comment by CANopenNode** [comment]
```-``` has a special meaning in Linux command shell. You should use:
* ```./canopencomm "16 write 0x3300 0 i32 -100"```
* ```./canopencomm 16 write 0x3300 0 u32 0xFFFFFFC8```

**Comment by OGCsolutions** [comment]
Thank you for quick reply. I came up with u32 solution but can not forgive myself that I did not notice obvious quote marks requirement.

**Comment by ZygaOGC** [comment]
Thank you for quick reply. I came up with u32 solution but can not forgive myself that I did not notice obvious quote marks requirement.
