### ISSUE TITLE
Adding LSS functionality

### ISSUE THREAD

**Issue by martinwag** [CANopenNode/CANopenSocket#4]
The same as for https://github.com/CANopenNode/CANopenNode/issues/47

I've added LSS to CANopenSocket (https://github.com/martinwag/CANopenSocket/tree/add-lss). Feel free to have a look, but be aware that this is still experimental. If you find errors or have other hints, please let me know :-)

**Comment by martinwag** [comment]
Added LSS Fastscan in my local repo. This now can automatically assign node IDs to all nodes in a network.

**Comment by geoffrey-vl** [comment]
this is merged, issue can be closed?
