### ISSUE TITLE
Syntax error with u64

### ISSUE THREAD

**Issue by kennethajonesii** [CANopenNode/CANopenSocket#8]
When executing the command 
`canopencomm 0x71 w 0x1000 0 u64 F000000000000070`

I get the following error:

`[1] ERROR: 101 - Syntax error. `

However, when I execute the command

`canopencomm 0x71 w 0x1000 0 u64 0000000000000070`

the command executes without issue.  I presume i am doing something, but I cannot see it.  Any assistance would be appreciated.

**Comment by martinwag** [comment]
What is the "F" supposed to do?
309-3 gives the following options for number format:
- dec (100)
- hex(0x64)
- float(100.0, 1e2)

**Comment by kennethajonesii** [comment]
The "F" is the highest nibble in a unsigned 64 integer.  Essentially it is 0xF000000000000070 (17293822569102704752 in decimal).  

I have tried entering this value in both hex and decimal forms.  I have also tried with pre-appending the "0x" before a hex value.  

Caneopencomm help "canopencomm -help"  does NOT specify these dec(), hex(), float(,) functions, so I am not sure how those help.

**Comment by martinwag** [comment]
those are not functions but examples for what is in the specification :-) . Have a look in CiA309-3 3.2.2. This also specifies endianness, so this is fixed.

**Comment by gpostolov** [comment]
In SDO the data max is 4 bytes!!!

For example:
My object 0x6000 00 is UNSIGNED64
`./canopencomm 4 read 0x6000 0 u64 `
`[1] 0x0000000000000000`
`./canopencomm 4 write 0x6000 0 u64 0x11223344`
`[1] OK`
` ./canopencomm 4 read 0x6000 0 u64`
`[1] 0x0000000011223344`
`./canopencomm 4 write 0x6000 0 u64 0x1122334455`
`[1] ERROR: 101 - Syntax error.`

It's only possible to write up to 0xFFFFFFFF (UNSIGNED32)

Is it possible to write with SDO the UNSIGNED64's object?

**Comment by martinwag** [comment]
Had a look at this. Works fine on 64 bit machine, but not on 32 bit.

open canopend/src/CO_comm_helpers.c, change 
ULONG_MAX -> ULLONG_MAX
LONG_MIN, LONG_MAX -> LLONG_MIN, LLONG_MAX

**Comment by gpostolov** [comment]
So so.
Now it's possible to write but not save correctly.
For example

```
./canopencomm 4 read 0x6000 0 u64
[1] 0x0000000000000000
./canopencomm 4 write 0x6000 0 u64 0x11223344
[1] OK
./canopencomm 4 read 0x6000 0 u64
[1] 0x0000000011223344
./canopencomm 4 write 0x6000 0 u64 0x1122334455
[1] OK
./canopencomm 4 read 0x6000 0 u64
[1] 0x0000000022334455
```

**Comment by martinwag** [comment]
This happens when you just "try to fix" something. I've now replaced the width indicators with the architecture indipendent ones, as has already been done for the variable types (uint64_t instead of unsigned long long int)

**Comment by geoffrey-vl** [comment]
This has been merged? If so please close
