### ISSUE TITLE
String / Domain encoding

### ISSUE THREAD

**Issue by martinwag** [CANopenNode/CANopenSocket#9]
Encoding for data types "os - octet string", "us - unicode string" and "d - domain" is currently hex-string. According to 309-3 this should be RFC2045 mime-base64.

**Comment by geoffrey-vl** [comment]
Is this still relevant? If not please close

**Comment by martinwag** [comment]
Yes, it is. It's more like do we want to change that (and lose compatibility) or keep it as it is (and violate CiA 309-3).

**Comment by geoffrey-vl** [comment]
I'd encourage staying as close to the specs as possible.

**Comment by CANopenNode** [comment]
TODO RFC2045 mime-base64

**Comment by CANopenNode** [comment]
RFC2045 mime-base64 is implemented in CANopenNode v2.0 and v4.0. See example https://github.com/CANopenNode/CANopenSocket/tree/master/examples/basicDevice
